export declare const UI_NAME = "lin-ui-vue";
export declare const CWD: string;
export declare const UI_CONFIG_DIR: string;
export declare const EJS: string;
export declare const ComponentTemplateEjs: string;
export declare const ComponentLessEjs: string;
export declare const ComponentIndexEjs: string;
export declare const ComponentPropsEjs: string;
export declare const ComponentExampleEjs: string;
export declare const ComponentDocsEjs: string;
export declare const ComponentDir: (componentName: string) => string;
export declare const UI_TYPES_DIR: string;
export declare const UI_PACKAGE_JSON: string;
export declare const UI_SRC_DIR: string;
export declare const UI_LIB_DIR: string;
export declare const UI_ES_DIR: string;
export declare const UI_EXAMPLE_DIR = "example";
export declare const UI_DOCS_DIR = "docs";
export declare const UI_BASE_DOC_DIR: string;
export declare const UI_COMPONENTS_DIR: string;
